formatter: "markdown table" # this is required

header-from: tfdocs/header.md
footer-from: tfdocs/footer.md

# recursive:
#   enabled: false
#   path: modules
#   include-main: true

sections:
  hide: []
  show: []

# content: ""

# output:
#   file: ""
#   mode: inject
#   template: |-
#     <!-- BEGIN_TF_DOCS -->
#     {{ .Content }}
#     <!-- END_TF_DOCS -->

# output-values:
#   enabled: false
#   from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
